# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            HooRay!
tagline:          'Brakujące ogniwo między HR a IT'
description:      'Społeczność ludzi zjednoczonych wokół ludzi.'
url:              hooray.community
baseurl:          /hooray.community

author:
  name:           Krzysztof (Chris) Miaskowski
  url:            https://www.linkedin.com/in/krzysztof-miaskowski/

paginate:         5

# Custom vars
version:          1.0.0-beta

github:
  repo:           https://github.com/hooray-community/hooray.community
